name: Codacy Analysis CI

on:
  push:
    branches: [ main, master ]   # triggers on both main & master
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:              # allows manual trigger

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3        # stable release tag

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master   # stable release
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
